name: aldonashea
favicon: null
layout_spectrum: 0.59884
typography_spectrum: 0.868074310477823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff8'
    - '#6996ad'
    - '#3f5b2b'
    - '#9b764a'
    - '#e8b245'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
