name: aldonashea
favicon: null
layout_spectrum: 0.47109
typography_spectrum: 0.83333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7faff'
    - '#809d5b'
    - '#1e1b14'
    - '#ffd607'
    - '#ff7629'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
